services:
  postgres:
    image: postgres:16-alpine
    container_name: yugiapp-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yugiapp-network

volumes:
  postgres_data:
    driver: local

networks:
  yugiapp-network:
    driver: bridge
