services:
  postgres:
    image: postgres:16-alpine
    container_name: yugiapp-db
    environment:
      POSTGRES_USER: api_yugiapp
      POSTGRES_PASSWORD: api_yugiapp@2024
      POSTGRES_DB: yugiapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yugiapp-network

volumes:
  postgres_data:
    driver: local

networks:
  yugiapp-network:
    driver: bridge
